name: CI

on:
  pull_request:
    branches:
      - ci
    paths:
      - '**sh'
      - '**py'
      - '**yaml'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: flexran test
      run: |
        cd automation
        if oc get --request-timeout='10s' node; then
            ./cleanup.sh || true
        fi
        ./start.sh
