name: CI

on:
  pull_request:
    branches:
      - ci
    paths:
      - '**sh'
      - '**py'
      - '**yaml'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run unittest
      run: |
        cd automation
        python3 -m unittest -v

  flexran:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: flexran initialization
      run: |
        cd automation
        if oc get --request-timeout='10s' node; then
            ./cleanup.sh || true
        fi
        ./start_initialize.sh
    - name: flexran setup
      run: |
        cd automation
        ./start_setup.sh
    - name: flexran timer mode test
      run: |
        cd automation
        ./start_timer.sh
    - name: flexran xran mode test
      run: |
        cd automation
        ./start_xran.sh
